package model;

import java.nio.file.Path;
import java.nio.file.WatchEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Represents a file system event such as create, modify, delete, or rename.
 * Each event is associated with a path, a timestamp, and keeps track of how
 * many times it has occurred.
 *
 * @author Abdulrahman Hassan and Kevin Kamau
 */
public class FileEvent {
    /**
     * The raw file event generated by the WatchService API.
     */
    private final WatchEvent<?> myFileEvent;

    /**
     * The base path where the file event occurred.
     */
    private final Path myPath;

    /**
     * A thread-safe counter that tracks how many times a specific file event has occurred.
     * The key is a string representation of the event type and file name.
     */
    private final static Map<String, Integer> myFileCounter = new ConcurrentHashMap<>();

    /**
     * A unique key that combines the event type and the file title, separated by a colon.
     */
    private final String myKey;

    /**
     * The timestamp when this event was created.
     */
    private final LocalDateTime myTimeStamp;

    /** Constant used when describing a file creation event. */
    private final static String CREATED_FILE_DIALOG = "created";

    /** Constant used when describing a file modification event. */
    private final static String MODIFIED_FILE_DIALOG = "modified";

    /** Constant used when describing a file deletion event. */
    private final static String DELETED_FILE_DIALOG = "deleted";

    /** Constant used when describing a file rename event. */
    private final static String RENAMED_FILE_DIALOG = "renamed";

    /**
     * Constructs a new FileEvent for the given WatchEvent and file path.
     * Also increments the internal counter for this type of event.
     *
     * @param theFileEvent the underlying watch event, cannot be null
     * @param thePath the base path associated with the event
     * @throws NullPointerException if the watch event is null
     */
    FileEvent(final WatchEvent<?> theFileEvent, final Path thePath) {
        if (theFileEvent == null) {
            throw new NullPointerException("event is null.");
        }

        myFileEvent = theFileEvent;
        myPath = thePath;
        myKey = eventType() + ":" + fileTitle();
        myTimeStamp = LocalDateTime.now();

        incrementCount();
    }

    /**
     * Increments the counter for this file event key.
     */
    private void incrementCount() {
        myFileCounter.put(myKey, myFileCounter.getOrDefault(myKey, 0) + 1);
    }

    /**
     * Retrieves how many times this event has occurred.
     *
     * @return the number of times this event has been recorded
     */
    public int getCount() {
        return myFileCounter.getOrDefault(myKey, 0);
    }

    /**
     * Resolves and returns the full path of the affected file.
     *
     * @return the complete file path of the event target
     */
    Path filePath() {
        return myPath.resolve((Path) myFileEvent.context());
    }

    /**
     * Returns the file name without its extension.
     *
     * @return the base file name
     */
    String fileName() {
        String name = fileTitle();
        int lastDot = name.lastIndexOf('.');
        if (lastDot > 0) {
            return name.substring(0, lastDot);
        }
        return name;
    }

    /**
     * Returns the file name with its extension included.
     *
     * @return the complete file title
     */
    String fileTitle() {
        return ((Path) myFileEvent.context()).getFileName().toString();
    }

    /**
     * Returns the type of this file event as a string.
     *
     * @return the event type
     */
    String eventType() {
        return myFileEvent.kind().name();
    }

    /**
     * Returns the file extension, if any.
     *
     * @return the file extension, or an empty string if none exists
     */
    String fileExtension() {
        String name = fileTitle();
        int lastDot = name.lastIndexOf('.');
        if (lastDot > 0 && lastDot < name.length() - 1) {
            return name.substring(lastDot + 1);
        }
        return "";
    }

    /**
     * Returns the exact timestamp when this event was created.
     *
     * @return the timestamp as a LocalDateTime
     */
    LocalDateTime getMyTimeStamp() {
        return myTimeStamp;
    }

    /**
     * Returns the timestamp formatted as a human-readable string.
     *
     * @return the formatted time string
     */
    String getTime() {
        DateTimeFormatter aFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        return getMyTimeStamp().format(aFormat);
    }

    /**
     * Creates a summary description of this file event.
     * Example: "document.txt was created in C:/Users/Example. This action was done 2 times. At 2025-08-22 10:30:15."
     *
     * @return a human-readable summary of the file event
     */
    public String eventSummary() {
        /*
           Example formatting of event kind into sentences:
           ENTRY_CREATE becomes "file was created in path. This was done X times."
        */
        return String.format(
                "%s was %s in %-10s. This action was done %d times. At %s.",
                fileTitle(),
                switch (eventType()) {
                    case "ENTRY_CREATE" -> CREATED_FILE_DIALOG;
                    case "ENTRY_MODIFY" -> MODIFIED_FILE_DIALOG;
                    case "ENTRY_DELETE" -> DELETED_FILE_DIALOG;
                    case "ENTRY_RENAME" -> RENAMED_FILE_DIALOG;
                    default -> throw new IllegalStateException("Unexpected value: " + myFileEvent.kind());
                },
                filePath(),
                getCount(),
                getTime()
        );
    }

    /**
     * Returns a string representation of the event key, which consists of the event type and file title.
     *
     * @return the string key of this event
     */
    public String toString() {
        return myKey;
    }
}
